### ISSUE TITLE
구동 방법을 README.md에 추가해주세요~

### ISSUE THREAD

**Issue by zrma** [jjori-master/hightchart-study#1]
@jjori-master 

parcel로 띄우면 되는건가요?

**Comment by jjori-master** [comment]
@zrma 
죄송합니다. 여기에 parcel을 부여하고 메뉴를 통해 공부사항을 보려 하였으나
아직 지원되지 않는 기능입니다.

대신 IDE/Chrome의확장 플러그인을 통해 보는 방법을 Readme.md에 기록하였습니다.
좋은 의견 감사드립니다.

[관련 Commit](https://github.com/jjori-master/hightchart-study/commit/d34f05249e836f0476366641c564a703cfc3359c)
